import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--color-bg) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-soft": "rgb(var(--color-surface-2) / <alpha-value>)",
        "surface-elevated": "rgb(var(--color-surface-elevated) / <alpha-value>)",
        "surface-overlay": "rgb(var(--color-surface-overlay) / <alpha-value>)",
        ink: "rgb(var(--color-text) / <alpha-value>)",
        muted: "rgb(var(--color-text-muted) / <alpha-value>)",
        subtle: "rgb(var(--color-text-subtle) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-strong": "rgb(var(--color-primary-strong) / <alpha-value>)",
        "primary-soft": "rgb(var(--color-primary-soft) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-soft": "rgb(var(--color-accent-soft) / <alpha-value>)",
        warm: "rgb(var(--color-warm) / <alpha-value>)",
        "warm-soft": "rgb(var(--color-warm-soft) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-soft": "rgb(var(--color-success-soft) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        "warning-soft": "rgb(var(--color-warning-soft) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        "danger-strong": "rgb(var(--color-danger-strong) / <alpha-value>)",
        "danger-soft": "rgb(var(--color-danger-soft) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        "info-soft": "rgb(var(--color-info-soft) / <alpha-value>)",
        neutral: "rgb(var(--color-neutral) / <alpha-value>)",
        "neutral-soft": "rgb(var(--color-neutral-soft) / <alpha-value>)",
        violet: "rgb(var(--color-violet) / <alpha-value>)",
        "violet-soft": "rgb(var(--color-violet-soft) / <alpha-value>)",
        coral: "rgb(var(--color-coral) / <alpha-value>)",
        "coral-soft": "rgb(var(--color-coral-soft) / <alpha-value>)",
        rose: "rgb(var(--color-rose) / <alpha-value>)",
        "rose-soft": "rgb(var(--color-rose-soft) / <alpha-value>)",
        teal: "rgb(var(--color-teal) / <alpha-value>)",
        "teal-soft": "rgb(var(--color-teal-soft) / <alpha-value>)",
        "surface-inverse": "rgb(var(--color-surface-inverse) / <alpha-value>)",
        "on-surface-inverse": "rgb(var(--color-on-surface-inverse) / <alpha-value>)",
        "on-surface-inverse-muted": "rgb(var(--color-on-surface-inverse-muted) / <alpha-value>)",
        "inverse-highlight": "rgb(var(--color-inverse-highlight) / <alpha-value>)",
        "surface-quiet": "rgb(var(--color-surface-quiet) / <alpha-value>)",
        "map-bg": "rgb(var(--color-map-bg) / <alpha-value>)",
        "map-road": "rgb(var(--color-map-road) / <alpha-value>)",
        "map-road-highlight": "rgb(var(--color-map-road-highlight) / <alpha-value>)",
        "map-secondary-road": "rgb(var(--color-map-secondary-road) / <alpha-value>)",
        "map-grid": "rgb(var(--color-map-grid) / <alpha-value>)",
        "map-route": "rgb(var(--color-map-route) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        "border-strong": "rgb(var(--color-border-strong) / <alpha-value>)",
        focus: "rgb(var(--color-focus) / <alpha-value>)",
        device: "rgb(var(--color-device) / <alpha-value>)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        floating: "var(--shadow-floating)",
        device: "var(--shadow-device)",
        card: "var(--shadow-sm)",
        button: "0 8px 18px -12px rgb(var(--color-primary) / 0.62)",
        nav: "0 -12px 28px -24px rgb(var(--color-text) / 0.48)",
        hero: "var(--shadow-hero)",
        inset: "var(--shadow-inset)",
      },
      borderRadius: {
        sm: "0.625rem",
        md: "0.875rem",
        lg: "1.125rem",
        xl: "1.5rem",
        control: "14px",
        card: "20px",
        sheet: "28px",
        feature: "28px",
      },
      spacing: {
        gutter: "var(--space-gutter)",
        content: "var(--space-content)",
        "inline-gap": "var(--space-inline-gap)",
        "control-gap": "var(--space-control-gap)",
        "card-gap": "var(--space-card-gap)",
        "section-gap": "var(--space-section-gap)",
      },
      fontSize: {
        xs: ["0.8125rem", { lineHeight: "1.25rem" }],
      },
    },
  },
  plugins: [],
};

export default config;
