"use client";

import { Check, ChevronRight, LockKeyhole, Volume2 } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
import { cn } from "@/lib/cn";

export function ProfileMain({ children }: { children: ReactNode }) { return <main className="app-scrollbar min-h-0 flex-1 overflow-y-auto px-5 py-5">{children}</main>; }
export function ProfileHeader({ name = "Анна Михайлова", city = "Москва", status = "Профиль подтверждён" }: { name?: string; city?: string; status?: string }) { return <Card className="p-5"><div className="flex items-start gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-primary-soft text-xl font-bold text-primary">АМ</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-ink">{name}</h2><Badge className="text-success">Проверен</Badge></div><p className="mt-1 text-sm text-muted">{city} · {status}</p><p className="mt-3 text-sm leading-6 text-muted">Интересы: кино, дизайн, прогулки</p></div></div></Card>; }
export function ProfileSection({ title, action, children }: { title: string; action?: ReactNode; children: ReactNode }) { return <section className="mt-6"><div className="flex items-end justify-between gap-3"><h2 className="text-lg font-bold text-ink">{title}</h2>{action}</div><div className="mt-3">{children}</div></section>; }
export function ProfileMenuItem({ href, title, description, icon, onClick }: { href?: string; title: string; description?: string; icon?: ReactNode; onClick?: () => void }) { const body = <><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary-soft text-primary">{icon ?? <ChevronRight aria-hidden="true" className="h-5 w-5" />}</span><span className="min-w-0 flex-1"><span className="block font-semibold text-ink">{title}</span>{description ? <span className="mt-1 block text-sm leading-5 text-muted">{description}</span> : null}</span><ChevronRight aria-hidden="true" className="h-5 w-5 shrink-0 text-muted" /></>; return href ? <Link href={href} className="flex min-h-16 items-center gap-3 rounded-control border border-border bg-surface p-3 hover:bg-surface-soft">{body}</Link> : <button type="button" onClick={onClick} className="flex min-h-16 w-full items-center gap-3 rounded-control border border-border bg-surface p-3 text-left hover:bg-surface-soft">{body}</button>; }
export function NeedSelector({ options, selected, onToggle }: { options: { key: string; label: string }[]; selected: string[]; onToggle: (key: string) => void }) { return <div className="grid gap-2 sm:grid-cols-2">{options.map((option) => { const active = selected.includes(option.key); return <button key={option.key} type="button" aria-pressed={active} onClick={() => onToggle(option.key)} className={cn("min-h-12 rounded-control border px-3 text-left text-sm font-semibold", active ? "border-primary bg-primary-soft text-primary" : "border-border bg-surface text-ink hover:bg-surface-soft")}>{active ? <Check aria-hidden="true" className="mr-2 inline h-4 w-4" /> : null}{option.label}</button>; })}</div>; }
export function ContentModeSelector({ value, onChange }: { value: "normal" | "simple" | "voice"; onChange: (value: "normal" | "simple" | "voice") => void }) { return <div className="grid gap-2 sm:grid-cols-3">{(["normal", "simple", "voice"] as const).map((mode) => <button key={mode} type="button" aria-pressed={value === mode} onClick={() => onChange(mode)} className={cn("min-h-12 rounded-control border px-3 text-sm font-semibold", value === mode ? "border-primary bg-primary-soft text-primary" : "border-border bg-surface text-ink")}>{mode === "normal" ? "Обычный" : mode === "simple" ? "Простой" : <><Volume2 aria-hidden="true" className="mr-1 inline h-4 w-4" />Голосовой</>}</button>)}</div>; }
export function SettingToggle({ label, description, checked, onChange }: { label: string; description?: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex min-h-16 cursor-pointer items-center justify-between gap-4 rounded-control border border-border bg-surface p-3"><span><span className="block font-semibold text-ink">{label}</span>{description ? <span className="mt-1 block text-sm text-muted">{description}</span> : null}</span><input type="checkbox" className="h-5 w-5 accent-primary" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label>; }
export function NotificationItem({ title, body, time, read, onClick }: { title: string; body?: string; time: string; read: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("w-full rounded-card border p-4 text-left", read ? "border-border bg-surface" : "border-primary/30 bg-primary-soft")}><div className="flex items-start justify-between gap-3"><span className="font-semibold text-ink">{title}</span><span className="shrink-0 text-xs text-muted">{time}</span></div>{body ? <p className="mt-2 text-sm leading-6 text-muted">{body}</p> : null}{!read ? <Badge className="mt-3 text-primary">Новое</Badge> : null}</button>; }
export function MyRequestCard({ request, href }: { request: { title: string; dateLabel: string; locationLabel: string; status: string }; href: string }) { const labels: Record<string, string> = { submitted: "Запрос создан", matching: "Ищем волонтёра", accepted: "Волонтёр найден", completed: "Завершено", cancelled: "Отменено", active: "Помощь идёт", volunteer_on_way: "Волонтёр в пути" }; return <Link href={href} className="block rounded-card border border-border bg-surface p-4 hover:bg-surface-soft"><div className="flex items-start justify-between gap-3"><h3 className="font-bold text-ink">{request.title}</h3><Badge>{labels[request.status] ?? request.status}</Badge></div><p className="mt-2 text-sm text-muted">{request.dateLabel} · {request.locationLabel}</p></Link>; }
export function MyPostCard({ title, body, date, href }: { title: string; body: string; date: string; href: string }) { return <Link href={href} className="block rounded-card border border-border bg-surface p-4 hover:bg-surface-soft"><Badge>Моя публикация</Badge><h3 className="mt-3 font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-muted">{body}</p><p className="mt-3 text-xs text-muted">{date}</p></Link>; }
export function AuthorOnboarding({ onComplete }: { onComplete: () => void }) { return <Card className="p-5"><Badge>Demo-режим</Badge><h2 className="mt-3 text-xl font-bold text-ink">Стать автором</h2><p className="mt-2 text-sm leading-6 text-muted">Рассказывайте о местах, маршрутах и личном опыте без публикации чувствительных данных.</p><ul className="mt-5 space-y-3 text-sm leading-6 text-ink"><li>✓ Выберите тему и понятный заголовок.</li><li>✓ Не указывайте адрес, телефон и медицинские сведения.</li><li>✓ Перед публикацией проверьте текст.</li></ul><Button className="mt-5 w-full" onClick={onComplete}>Подтвердить и продолжить</Button></Card>; }
export function CreatePostForm({ onSubmit }: { onSubmit: (title: string, body: string) => void }) { return <form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get("title") ?? "").trim(); const body = String(form.get("body") ?? "").trim(); if (title && body) onSubmit(title, body); }}><label className="block text-sm font-semibold text-ink">Заголовок<Input name="title" className="mt-2" required placeholder="Например, как я готовлю маршрут" /></label><label className="block text-sm font-semibold text-ink">Текст<Textarea name="body" className="mt-2" required placeholder="Поделитесь полезным опытом" /></label><Button type="submit" className="w-full">Опубликовать в ленте</Button></form>; }
export function PaperworkProgress({ stages, completed, onToggle }: { stages: { id: string; title: string; detail: string }[]; completed: string[]; onToggle: (id: string, value: boolean) => void }) { return <div className="space-y-3">{stages.map((stage) => <label key={stage.id} className="flex gap-3 rounded-card border border-border bg-surface p-4"><input type="checkbox" className="mt-1 h-5 w-5 accent-primary" checked={completed.includes(stage.id)} onChange={(event) => onToggle(stage.id, event.target.checked)} /><span><span className="block font-semibold text-ink">{stage.title}</span><span className="mt-1 block text-sm leading-5 text-muted">{stage.detail}</span></span></label>)}</div>; }
export function ProfileCompleteness({ percent }: { percent: number }) { return <Card className="border-primary/20 bg-primary-soft p-4"><p className="text-sm font-semibold text-primary">Профиль заполнен на {percent}%</p><p className="mt-1 text-sm leading-5 text-muted">Это подсказка для удобства рекомендаций, а не обязательная оценка.</p></Card>; }
export function TextField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold text-ink">{label}<Input className="mt-2" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
export function SecurityCard({ enabled, onChange }: { enabled: boolean; onChange: (value: boolean) => void }) { return <Card className="p-5"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 h-5 w-5 text-primary" /><div><h2 className="font-bold text-ink">Защита приложения</h2><p className="mt-1 text-sm leading-6 text-muted">Функция включается только в demo-сценарии и не создаёт настоящую авторизацию.</p></div></div><SettingToggle label="Запрашивать PIN при открытии" checked={enabled} onChange={onChange} /></Card>; }
