"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Bell, BookOpen, BriefcaseBusiness, Heart, Info, MapPin, MessageCircleQuestion, Settings2, ShieldCheck, Users, WalletCards } from "lucide-react";
import { routes } from "@/lib/routes";
import { useDemoStore } from "@/store/demoStore";
import { places } from "@/data/seed";
import { opportunityCourses, opportunityEvents, opportunityOrganizations, opportunityVacancies } from "@/data/opportunities";
import { socialPosts } from "@/data/social";
import { paperworkStages } from "@/data/profile";
import type { UserNeedKey } from "@/types";
import { ResumeView } from "@/components/opportunities/OpportunityComponents";
import { EmptyState } from "@/components/ui/EmptyState";
import { Toast } from "@/components/ui/Toast";
import { Modal } from "@/components/ui/Modal";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { ProfileCompleteness, ProfileHeader, ProfileMain, ProfileMenuItem, ProfileSection, NeedSelector, ContentModeSelector, SettingToggle, NotificationItem, MyRequestCard, MyPostCard, AuthorOnboarding, CreatePostForm, PaperworkProgress, SecurityCard } from "@/components/profile/ProfileComponents";
import { AppScreenHeader } from "@/components/demo/AppScreenHeader";

const needGroups: { title: string; options: { key: UserNeedKey; label: string }[] }[] = [
  { title: "Передвижение и вход", options: [{ key: "step_free", label: "Без ступеней" }, { key: "elevator", label: "Нужен лифт" }, { key: "wide_doors", label: "Широкие двери и проходы" }, { key: "accessible_parking", label: "Доступная парковка" }, { key: "assistance", label: "Сопровождение" }] },
  { title: "Навигация и восприятие", options: [{ key: "high_contrast", label: "Высокий контраст" }, { key: "large_text", label: "Крупный текст" }, { key: "screen_reader", label: "Экранный диктор и визуальная информация" }, { key: "voice_hints", label: "Голосовые подсказки" }, { key: "tactile_navigation", label: "Тактильная навигация" }] },
  { title: "Коммуникация и темп", options: [{ key: "hearing_support", label: "Поддержка слуха" }, { key: "quiet_zone", label: "Тихая зона" }, { key: "accessible_toilet", label: "Доступный туалет" }, { key: "simple_mode", label: "Простой язык" }] },
];
const needLabel = Object.fromEntries(needGroups.flatMap((group) => group.options.map((item) => [item.key, item.label])));
function SubHeader({ title }: { title: string }) { return <AppScreenHeader title={title} backHref={routes.user.profile} compact />; }
function LinkButton({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex min-h-11 items-center justify-center rounded-control bg-primary px-4 text-sm font-semibold text-white">{children}</Link>; }

export function ProfileHomeScreen() {
  const state = useDemoStore();
  const unread = state.notifications.filter((item) => !item.read).length;
  const requests = state.helpRequests.filter((item) => item.createdBy === "user_anna");
  const percent = Math.round(([state.userNeeds.length > 0, state.resume.title.length > 0, state.resume.skills.length > 0, state.contactPermissions.whoCanRequest !== "nobody"].filter(Boolean).length / 4) * 100);
  return <ProfileMain><ProfileHeader /><div className="mt-5 grid grid-cols-4 gap-2">{[[state.friendIds.length, "Друзья", routes.user.profileFriends], [state.favoriteIds.length, "Избранное", routes.user.profileFavorites], [requests.length, "Запросы", routes.user.profileRequests], [state.userCreatedPosts.length + socialPosts.filter((post) => post.authorId === "user_anna").length, "Посты", routes.user.profilePosts]].map(([value, label, href]) => <Link key={String(label)} href={String(href)} className="rounded-card border border-border bg-surface p-3 text-center"><p className="text-xl font-bold text-primary">{value}</p><p className="mt-1 text-xs text-muted">{label}</p></Link>)}</div><div className="mt-5"><ProfileCompleteness percent={percent} /></div><ProfileSection title="Главное"><div className="space-y-2"><ProfileMenuItem href={routes.user.profileAccessibility} title="Профиль доступности" description={state.userNeeds.length ? `${state.userNeeds.length} важных условий учтены` : "Добавьте условия, которые важно учитывать"} icon={<ShieldCheck className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileResume} title="Резюме и возможности" description="Продолжить работу с резюме и вакансиями" icon={<BriefcaseBusiness className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileNotifications} title="Уведомления" description={unread ? `${unread} непрочитанных` : "Всё прочитано"} icon={<Bell className="h-5 w-5" />} /></div></ProfileSection><ProfileSection title="Общение и данные"><div className="space-y-2"><ProfileMenuItem href={routes.user.profileFriends} title="Друзья" icon={<Users className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileContactPermissions} title="Контакты и приватность" icon={<ShieldCheck className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profilePosts} title="Мои публикации" icon={<BookOpen className="h-5 w-5" />} /></div></ProfileSection><ProfileSection title="Настройки и помощь"><div className="space-y-2"><ProfileMenuItem href={routes.user.profileAppearance} title="Внешний вид и режим чтения" icon={<Settings2 className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileSecurity} title="Безопасность" /><ProfileMenuItem href={routes.user.profileApp} title="Приложение" /><ProfileMenuItem href={routes.user.profileHelp} title="Помощь" icon={<MessageCircleQuestion className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileAbout} title="О Навигаторе" icon={<Info className="h-5 w-5" />} /><ProfileMenuItem href={routes.user.profileTransactions} title="История действий" icon={<WalletCards className="h-5 w-5" />} /></div></ProfileSection></ProfileMain>;
}

export function AccessibilityProfileScreen({ edit = false }: { edit?: boolean }) {
  const userNeeds = useDemoStore((state) => state.userNeeds); const update = useDemoStore((state) => state.actions.updateUserNeeds); const [draft, setDraft] = useState(userNeeds); const [toast, setToast] = useState<string | null>(null); const router = useRouter();
  useEffect(() => { setDraft(userNeeds); }, [userNeeds]);
  if (!edit) return <ProfileMain><SubHeader title="Профиль доступности" /><Card className="border-primary/20 bg-primary-soft p-5"><h3 className="font-bold text-ink">Что важно учитывать</h3><p className="mt-2 text-sm leading-6 text-muted">Эти настройки помогают карте и рекомендациям подбирать подходящие условия. Диагнозы и медицинские сведения не нужны.</p><div className="mt-4 flex flex-wrap gap-2">{userNeeds.length ? userNeeds.map((need) => <Badge key={need}>{needLabel[need] ?? need}</Badge>) : <span className="text-sm text-muted">Пока ничего не выбрано</span>}</div></Card><LinkButton href={routes.user.profileAccessibilityEdit}>Изменить потребности</LinkButton></ProfileMain>;
  const toggle = (key: string) => setDraft((current) => current.includes(key as UserNeedKey) ? current.filter((item) => item !== key) : [...current, key as UserNeedKey]);
  return <ProfileMain><SubHeader title="Что учитывать в маршрутах" />{needGroups.map((group) => <ProfileSection key={group.title} title={group.title}><NeedSelector options={group.options} selected={draft} onToggle={toggle} /></ProfileSection>)}<Button className="mt-6 w-full" onClick={() => { update(draft); setToast("Профиль доступности сохранён"); router.push(routes.user.profileAccessibility); }}>Сохранить изменения</Button><Toast message={toast} onDismiss={() => setToast(null)} /></ProfileMain>;
}

export function AppearanceScreen() { const settings = useDemoStore((state) => state.settings); const patch = useDemoStore((state) => state.actions.patchSettings); const [toast, setToast] = useState<string | null>(null); const save = (value: Parameters<typeof patch>[0]) => { patch(value); setToast("Настройки сохранены"); }; return <ProfileMain><SubHeader title="Внешний вид и режим чтения" /><ProfileSection title="Режим чтения"><ContentModeSelector value={settings.contentMode} onChange={(contentMode) => save({ contentMode, voiceHints: contentMode === "voice" || settings.voiceHints })} /></ProfileSection><ProfileSection title="Тема"><div className="grid grid-cols-3 gap-2">{(["light", "dark", "system"] as const).map((theme) => <button key={theme} type="button" aria-pressed={settings.theme === theme} onClick={() => save({ theme })} className={`min-h-12 rounded-control border px-3 text-sm font-semibold ${settings.theme === theme ? "border-primary bg-primary-soft text-primary" : "border-border bg-surface"}`}>{theme === "light" ? "Светлая" : theme === "dark" ? "Тёмная" : "Системная"}</button>)}</div></ProfileSection><ProfileSection title="Размер и контраст"><label className="block text-sm font-semibold text-ink">Размер текста<select aria-label="Размер текста" value={settings.textScale} onChange={(event) => save({ textScale: Number(event.target.value) as 1 | 1.25 | 1.5 })} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3"><option value="1">100%</option><option value="1.25">125%</option><option value="1.5">150%</option></select></label><div className="mt-3 space-y-2"><SettingToggle label="Высокий контраст" checked={settings.highContrast} onChange={(highContrast) => save({ highContrast })} /><SettingToggle label="Уменьшить движение" checked={settings.reducedMotion} onChange={(reducedMotion) => save({ reducedMotion })} /><SettingToggle label="Голосовые подсказки" checked={settings.voiceHints} onChange={(voiceHints) => save({ voiceHints })} /></div></ProfileSection><Toast message={toast} onDismiss={() => setToast(null)} /></ProfileMain>; }

export function NotificationsScreen({ settingsOnly = false }: { settingsOnly?: boolean }) { const state = useDemoStore(); const [toast, setToast] = useState<string | null>(null); if (settingsOnly) return <NotificationSettingsScreen />; const groups = [{ id: "today", title: "Сегодня" }, { id: "yesterday", title: "Вчера" }, { id: "earlier", title: "Ранее" }]; const userNotifications = state.notifications.filter((item) => item.userId === "user_anna"); return <ProfileMain><SubHeader title="Уведомления" /><div className="flex flex-wrap gap-2"><Badge>{userNotifications.filter((item) => !item.read).length} непрочитанных</Badge><Link href={routes.user.profileNotificationSettings} className="text-sm font-semibold text-primary">Настроить уведомления</Link><Button size="sm" variant="secondary" onClick={() => { userNotifications.filter((item) => !item.read).forEach((item) => state.actions.markNotificationRead(item.id)); setToast("Все уведомления отмечены прочитанными"); }}>Прочитать всё</Button></div>{groups.map((group) => { const items = userNotifications.filter((item) => item.dateGroup === group.id); return <ProfileSection key={group.id} title={group.title}>{items.length ? <div className="space-y-2">{items.map((item) => <NotificationItem key={item.id} title={item.title} body={item.body} time={item.timeLabel} read={item.read} onClick={() => { state.actions.markNotificationRead(item.id); if (item.deepLink) window.location.assign(item.deepLink); }} />)}</div> : <EmptyState title="Нет уведомлений" description="Для этого периода сообщений нет." />}</ProfileSection>; })}<Toast message={toast} onDismiss={() => setToast(null)} /></ProfileMain>; }
export function NotificationSettingsScreen() { const settings = useDemoStore((state) => state.notificationPreferences); const update = useDemoStore((state) => state.actions.updateNotificationPreferences); const categories = [["help", "Помощь"], ["map", "Карта"], ["work", "Работа"], ["learning", "Обучение"], ["events", "События"], ["community", "Сообщество"], ["partnerOffers", "Партнёрские предложения"]] as const; return <ProfileMain><SubHeader title="Настройки уведомлений" /><div className="space-y-2">{categories.map(([key, label]) => <SettingToggle key={key} label={label} checked={settings[key]} onChange={(value) => update({ [key]: value })} />)}</div><ProfileSection title="Тихие часы"><SettingToggle label="Включить тихие часы" checked={settings.quietHoursEnabled} onChange={(quietHoursEnabled) => update({ quietHoursEnabled })} /><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-sm font-semibold">С <input type="time" value={settings.quietHoursStart} onChange={(event) => update({ quietHoursStart: event.target.value })} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3" /></label><label className="text-sm font-semibold">До <input type="time" value={settings.quietHoursEnd} onChange={(event) => update({ quietHoursEnd: event.target.value })} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3" /></label></div></ProfileSection></ProfileMain>; }

export function ContactPermissionsScreen() { const value = useDemoStore((state) => state.contactPermissions); const update = useDemoStore((state) => state.actions.updateContactPermissions); return <ProfileMain><SubHeader title="Контакты и приватность" /><Card className="p-4"><p className="text-sm leading-6 text-muted">Настройки применяются только к тестовым профилям. Реальные контакты не публикуются.</p><label className="mt-4 block text-sm font-semibold">Кто может попросить контакт<select value={value.whoCanRequest} onChange={(event) => update({ whoCanRequest: event.target.value as typeof value.whoCanRequest })} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3"><option value="friends">Только друзья</option><option value="common_communities">Общие сообщества</option><option value="request">После запроса</option><option value="nobody">Никто</option></select></label></Card><div className="mt-3 space-y-2"><SettingToggle label="Показывать Telegram после подтверждения" checked={value.showTelegramAfterConfirmation} onChange={(showTelegramAfterConfirmation) => update({ showTelegramAfterConfirmation })} /><SettingToggle label="Показывать электронную почту после подтверждения" checked={value.showEmailAfterConfirmation} onChange={(showEmailAfterConfirmation) => update({ showEmailAfterConfirmation })} /></div></ProfileMain>; }

export function ResumeProfileScreen() { const resume = useDemoStore((state) => state.resume); return <ProfileMain><SubHeader title="Резюме" /><ResumeView resume={resume} onEdit={() => window.location.assign(routes.user.resumeEdit)} /><LinkButton href={routes.user.vacancies}>Открыть возможности</LinkButton></ProfileMain>; }
export function PaperworkScreen() { const state = useDemoStore(); return <ProfileMain><SubHeader title="Документы и справочные шаги" /><Card className="border-warning/30 bg-warning-soft p-4"><p className="text-sm leading-6 text-warning"><strong>Важно:</strong> это демонстрационный чек-лист. Он не заменяет консультацию и не является государственной или юридической инструкцией. Не отправляйте документы в demo-приложение.</p></Card><ProfileSection title="Мой чек-лист"><PaperworkProgress stages={paperworkStages} completed={state.paperworkProgress.completedStageIds} onToggle={state.actions.updatePaperworkProgress} /></ProfileSection><p className="mt-4 text-sm text-muted">Для проверки официального порядка используйте первоисточник или специалиста из раздела «Помощь».</p></ProfileMain>; }
export function RequestsScreen() { const helpRequests = useDemoStore((state) => state.helpRequests); const requests = helpRequests.filter((item) => item.createdBy === "user_anna"); const active = requests.filter((item) => !["completed", "cancelled"].includes(item.status)); const completed = requests.filter((item) => item.status === "completed"); return <ProfileMain><SubHeader title="Мои запросы помощи" /><ProfileSection title="Активные"><div className="space-y-2">{active.length ? active.map((item) => <MyRequestCard key={item.id} request={item} href={routes.user.helpRequest(item.id)} />) : <EmptyState title="Активных запросов нет" description="Создать запрос можно в разделе «Помощь»." action={<LinkButton href={routes.user.help}>Открыть помощь</LinkButton>} />}</div></ProfileSection><ProfileSection title="Завершённые"><div className="space-y-2">{completed.length ? completed.map((item) => <MyRequestCard key={item.id} request={item} href={routes.user.helpRequest(item.id)} />) : <p className="text-sm text-muted">Завершённых запросов пока нет.</p>}</div></ProfileSection></ProfileMain>; }

export function PostsScreen() { const state = useDemoStore(); const posts = [...state.userCreatedPosts, ...socialPosts.filter((post) => post.authorId === "user_anna")]; return <ProfileMain><SubHeader title="Мои публикации" />{!state.isAuthor ? <AuthorOnboarding onComplete={() => state.actions.setAuthor(true)} /> : <><div className="flex items-center justify-between gap-3"><Badge className="text-success">Автор включён</Badge><Link href={routes.user.profileBecomeAuthor} className="text-sm font-semibold text-primary">Правила</Link></div><div className="mt-4"><CreatePostForm onSubmit={(title, body) => state.actions.createPost({ title, body, type: "experience", tags: ["опыт"], media: [] })} /></div></>}{posts.length ? <ProfileSection title="Опубликовано"><div className="space-y-2">{posts.map((post) => <MyPostCard key={post.id} title={post.title} body={post.body} date={post.dateLabel} href={routes.user.post(post.id)} />)}</div></ProfileSection> : <ProfileSection title="Пока пусто"><EmptyState title="Публикаций нет" description={state.isAuthor ? "Создайте первую публикацию выше." : "После регистрации автора здесь появятся ваши тексты."} /></ProfileSection>}</ProfileMain>; }
export function BecomeAuthorScreen() { const state = useDemoStore(); const router = useRouter(); return <ProfileMain><SubHeader title="Стать автором" /><AuthorOnboarding onComplete={() => { state.actions.setAuthor(true); router.push(routes.user.profilePosts); }} /></ProfileMain>; }

export function FavoritesProfileScreen() { const favoriteIds = useDemoStore((state) => state.favoriteIds); const savedArticles = useDemoStore((state) => state.savedArticleIds); const all = [{ kind: "places", label: "Места", items: places.map((item) => ({ id: item.id, title: item.name, href: routes.user.place(item.id), icon: <MapPin className="h-4 w-4" /> })) }, { kind: "work", label: "Вакансии", items: opportunityVacancies.map((item) => ({ id: item.id, title: item.title, href: routes.user.vacancy(item.id), icon: <BriefcaseBusiness className="h-4 w-4" /> })) }, { kind: "learning", label: "Курсы", items: opportunityCourses.map((item) => ({ id: item.id, title: item.title, href: routes.user.course(item.id), icon: <BookOpen className="h-4 w-4" /> })) }, { kind: "events", label: "События", items: opportunityEvents.map((item) => ({ id: item.id, title: item.title, href: routes.user.event(item.id), icon: <Info className="h-4 w-4" /> })) }, { kind: "orgs", label: "Организации", items: opportunityOrganizations.map((item) => ({ id: item.id, title: item.name, href: routes.user.organization(item.id), icon: <Users className="h-4 w-4" /> })) }]; const filtered = all.flatMap((group) => group.items.filter((item) => favoriteIds.includes(item.id) || (group.kind === "learning" && savedArticles.includes(item.id)))); return <ProfileMain><SubHeader title="Избранное" />{filtered.length ? <div className="space-y-2">{filtered.map((item) => <Link key={item.id} href={item.href} className="flex min-h-14 items-center gap-3 rounded-control border border-border bg-surface p-3 hover:bg-surface-soft"><span className="text-primary">{item.icon}</span><span className="font-semibold text-ink">{item.title}</span><Heart className="ml-auto h-4 w-4 fill-danger text-danger" /></Link>)}</div> : <EmptyState title="Избранное пока пусто" description="Сохраняйте места, вакансии, курсы и события через кнопку с сердцем." action={<LinkButton href={routes.user.map}>Открыть карту</LinkButton>} />}</ProfileMain>; }

export function SecurityScreen() { const value = useDemoStore((state) => state.securitySettings); const update = useDemoStore((state) => state.actions.updateSecuritySettings); return <ProfileMain><SubHeader title="Безопасность" /><SecurityCard enabled={value.appProtectionEnabled} onChange={(appProtectionEnabled) => update({ appProtectionEnabled })} /><Card className="mt-4 p-4"><h3 className="font-bold text-ink">Активная demo-сессия</h3><p className="mt-2 text-sm leading-6 text-muted">Устройство: текущий браузер. Настоящего входа, пароля и передачи данных нет.</p></Card></ProfileMain>; }
export function AppSettingsScreen() { const actions = useDemoStore((state) => state.actions); const router = useRouter(); const [open, setOpen] = useState(false); return <ProfileMain><SubHeader title="Приложение" /><div className="space-y-2"><ProfileMenuItem title="Язык" description="Русский" /><ProfileMenuItem title="Поведение карты" description="Показывать список мест" /><ProfileMenuItem title="Локальные demo-данные" description="Хранятся только в этом браузере" /></div><Button variant="danger" className="mt-6 w-full" onClick={() => setOpen(true)}>Сбросить demo</Button><p className="mt-4 text-center text-xs text-muted">Версия demo 0.1 · без авторизации и внешних API</p><Modal open={open} title="Сбросить demo-данные?" onClose={() => setOpen(false)}><p className="text-sm leading-6 text-muted">Изменения профиля, избранного, настроек и публикаций будут удалены.</p><Button variant="danger" className="mt-5 w-full" onClick={() => { actions.resetDemo(); router.push(routes.demo); }}>Сбросить</Button></Modal></ProfileMain>; }
export function AboutScreen() { return <ProfileMain><SubHeader title="О Навигаторе" /><Card className="p-5"><h2 className="text-xl font-bold text-ink">Навигатор доступности</h2><p className="mt-3 leading-7 text-ink">Демо-продукт помогает находить доступные места, получать помощь, читать опыт сообщества и выбирать возможности.</p><div className="mt-5 space-y-3 text-sm leading-6 text-muted"><p><strong className="text-ink">Статус:</strong> демонстрационный сценарий.</p><p><strong className="text-ink">Приватность:</strong> данные профиля и настройки хранятся локально.</p><p><strong className="text-ink">Обратная связь:</strong> используйте раздел «Помощь».</p></div></Card></ProfileMain>; }
export function ProfileHelpScreen() { return <ProfileMain><SubHeader title="Помощь по профилю" /><div className="space-y-2"><ProfileMenuItem href={routes.user.profileAccessibility} title="Настроить доступность" description="Потребности, язык и голосовые подсказки" /><ProfileMenuItem href={routes.user.profileAppearance} title="Изменить отображение" description="Размер текста, контраст и режим чтения" /><ProfileMenuItem href={routes.user.help} title="Задать вопрос" description="Перейти в общий раздел помощи" /><ProfileMenuItem href={routes.user.helpQuestion} title="Сообщить о проблеме" description="Тестовый вопрос для команды навигации" /></div></ProfileMain>; }
export function TransactionsScreen() { return <ProfileMain><SubHeader title="История действий" /><Card className="p-5"><WalletCards className="h-7 w-7 text-primary" /><h2 className="mt-3 font-bold text-ink">Тестовая история</h2><p className="mt-2 text-sm leading-6 text-muted">Платежей и настоящих транзакций нет. Здесь будет отображаться история демонстрационных действий, если она понадобится на следующем этапе.</p></Card><EmptyState title="Пока нет операций" description="Этот раздел намеренно оставлен демонстрационным." /></ProfileMain>; }
