"use client";

import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, Check, Clock3, GraduationCap, Heart, MapPin, Users } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import type { Organization, Resume } from "@/types";
import type { Club, OpportunityCourse, OpportunityEvent, OpportunityVacancy, PartnerOffer } from "@/types/opportunities";
import { routes } from "@/lib/routes";
import { cn } from "@/lib/cn";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";

export function OpportunitySection({ title, eyebrow, action, children }: { title: string; eyebrow?: string; action?: React.ReactNode; children: React.ReactNode }) {
  return <section aria-labelledby={title.replaceAll(" ", "-")} className="mt-7"><div className="flex items-end justify-between gap-3"><div>{eyebrow ? <p className="text-xs font-semibold uppercase tracking-[0.08em] text-muted">{eyebrow}</p> : null}<h2 id={title.replaceAll(" ", "-")} className="mt-1 text-xl font-bold text-ink">{title}</h2></div>{action}</div><div className="mt-3">{children}</div></section>;
}

export function RecommendationReason({ children }: { children: React.ReactNode }) {
  return <p className="flex items-start gap-2 text-sm leading-5 text-primary"><span className="mt-0.5 inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-primary-soft"><Check aria-hidden="true" className="h-3.5 w-3.5" /></span><span>Почему подходит: {children}</span></p>;
}

function FavoriteButton({ active, label, onClick }: { active: boolean; label: string; onClick?: () => void }) {
  if (!onClick) return null;
  return <button type="button" onClick={onClick} aria-label={active ? `Убрать «${label}» из избранного` : `Добавить «${label}» в избранное`} aria-pressed={active} className="inline-flex h-11 w-11 items-center justify-center rounded-control text-muted hover:bg-surface-soft"><Heart aria-hidden="true" className={cn("h-5 w-5", active && "fill-danger text-danger")} /></button>;
}

function OpportunityMeta({ children }: { children: React.ReactNode }) { return <div className="mt-3 flex flex-wrap gap-2 text-sm text-muted">{children}</div>; }

export function VacancyCard({ vacancy, organization, favorite, onFavorite }: { vacancy: OpportunityVacancy; organization?: Organization; favorite?: boolean; onFavorite?: (id: string) => void }) {
  return <Card className="p-4"><div className="flex items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2"><Badge>{vacancy.workMode === "remote" ? "Удалённо" : vacancy.workMode === "hybrid" ? "Гибрид" : "В офисе"}</Badge>{vacancy.status === "closed" ? <Badge className="bg-danger/10 text-danger">Закрыта</Badge> : <Badge className="text-success">Открыта</Badge>}</div><Link href={routes.user.vacancy(vacancy.id)} className="mt-3 block rounded-control focus:outline-none focus:ring-2 focus:ring-focus"><h3 className="text-lg font-bold text-ink">{vacancy.title}</h3><p className="mt-1 text-sm text-muted">{organization?.name ?? "Партнёр Навигатора"}</p></Link></div><FavoriteButton active={Boolean(favorite)} label={vacancy.title} onClick={() => onFavorite?.(vacancy.id)} /></div><OpportunityMeta><span className="inline-flex items-center gap-1"><BriefcaseBusiness aria-hidden="true" className="h-4 w-4" />{vacancy.city}</span><span className="inline-flex items-center gap-1"><Clock3 aria-hidden="true" className="h-4 w-4" />{vacancy.schedule}</span></OpportunityMeta><p className="mt-3 text-sm leading-6 text-muted">{vacancy.description}</p><div className="mt-3 flex flex-wrap gap-2">{vacancy.accessibilityConditions.slice(0, 3).map((item) => <Badge key={item}>{item}</Badge>)}</div>{vacancy.recommendationTags[0] ? <div className="mt-4"><RecommendationReason>{vacancy.recommendationTags[0]}</RecommendationReason></div> : null}<Link href={routes.user.vacancy(vacancy.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control bg-primary text-sm font-semibold text-white">Подробнее<ArrowUpRight aria-hidden="true" className="ml-2 h-4 w-4" /></Link></Card>;
}

export function VacancyFilters({ onApply }: { onApply: (filters: { query: string; workMode: string; category: string }) => void }) {
  const [query, setQuery] = useState(""); const [workMode, setWorkMode] = useState("all"); const [category, setCategory] = useState("all");
  return <Card className="p-4"><label htmlFor="vacancy-search" className="text-sm font-semibold text-ink">Поиск вакансий</label><Input id="vacancy-search" className="mt-2" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Название, навык или организация" /><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-ink">Формат<select value={workMode} onChange={(event) => setWorkMode(event.target.value)} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3 text-base font-normal"><option value="all">Любой</option><option value="remote">Удалённо</option><option value="hybrid">Гибрид</option><option value="office">В офисе</option></select></label><label className="text-sm font-semibold text-ink">Направление<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 min-h-12 w-full rounded-control border border-border bg-surface px-3 text-base font-normal"><option value="all">Любое</option><option value="design">Дизайн</option><option value="research">Исследования</option><option value="support">Поддержка</option><option value="content">Контент</option><option value="development">Разработка</option></select></label></div><Button className="mt-4 w-full" onClick={() => onApply({ query, workMode, category })}>Показать вакансии</Button></Card>;
}

export function VacancyDetail({ vacancy, organization, applied, favorite, onApply, onFavorite }: { vacancy: OpportunityVacancy; organization?: Organization; applied: boolean; favorite: boolean; onApply: () => void; onFavorite: () => void }) {
  return <div className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge>{vacancy.status === "open" ? "Вакансия открыта" : "Вакансия закрыта"}</Badge><h1 className="mt-3 text-2xl font-bold leading-tight text-ink">{vacancy.title}</h1><p className="mt-2 text-sm text-muted">{organization?.name ?? "Организация не найдена"} · {vacancy.city}</p></div><FavoriteButton active={favorite} label={vacancy.title} onClick={onFavorite} /></div><p className="mt-5 leading-7 text-ink">{vacancy.description}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-control bg-surface-soft p-3"><p className="text-xs text-muted">Формат</p><p className="mt-1 font-semibold text-ink">{vacancy.workMode === "remote" ? "Удалённая работа" : vacancy.workMode === "hybrid" ? "Гибрид" : "Офис"}</p></div><div className="rounded-control bg-surface-soft p-3"><p className="text-xs text-muted">Вознаграждение</p><p className="mt-1 font-semibold text-ink">{vacancy.salaryRange ?? "Обсуждается"}</p></div></div>{applied ? <div className="mt-5 rounded-control bg-success/10 p-4 text-sm font-semibold text-success" role="status">Вы уже откликнулись на эту вакансию. Повторная заявка не создаётся.</div> : <Button className="mt-5 w-full" disabled={vacancy.status === "closed"} onClick={onApply}>{vacancy.status === "closed" ? "Вакансия закрыта" : "Откликнуться"}</Button>}</Card><Card className="p-4"><h2 className="font-bold text-ink">Условия доступности</h2><ul className="mt-3 space-y-2">{vacancy.accessibilityConditions.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-ink"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-success" />{item}</li>)}</ul></Card><Card className="p-4"><h2 className="font-bold text-ink">Что понадобится</h2><div className="mt-3 flex flex-wrap gap-2">{vacancy.requirements.concat(vacancy.skills).map((item) => <Badge key={item}>{item}</Badge>)}</div></Card>{organization ? <Link href={routes.user.organization(organization.id)} className="inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть организацию<ArrowUpRight aria-hidden="true" className="ml-2 h-4 w-4" /></Link> : null}</div>;
}

export function ResumeView({ resume, onEdit }: { resume: Resume; onEdit: () => void }) {
  return <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge>Ваше резюме</Badge><h1 className="mt-3 text-2xl font-bold text-ink">{resume.title || "Резюме пока не заполнено"}</h1></div><Button size="sm" variant="secondary" onClick={onEdit}>Изменить</Button></div>{resume.summary ? <p className="mt-5 leading-7 text-ink">{resume.summary}</p> : <p className="mt-5 text-sm text-muted">Добавьте короткое описание, чтобы рекомендации стали точнее.</p>}<ResumeBlock title="Навыки" items={resume.skills} empty="Навыки ещё не добавлены" /><ResumeBlock title="Опыт" items={resume.experience} empty="Опыт ещё не добавлен" /><ResumeBlock title="Предпочтительный формат" items={resume.preferredWorkMode.map((mode) => mode === "remote" ? "Удалённо" : mode === "hybrid" ? "Гибрид" : "Офис")} empty="Формат не выбран" /><ResumeBlock title="Условия" items={resume.accessibilityNeeds ?? []} empty="Особые условия не указаны" /></Card>;
}
function ResumeBlock({ title, items, empty }: { title: string; items: string[]; empty: string }) { return <section className="mt-6 border-t border-border pt-4"><h2 className="font-bold text-ink">{title}</h2>{items.length ? <ul className="mt-2 space-y-2 text-sm leading-6 text-ink">{items.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-2 text-sm text-muted">{empty}</p>}</section>; }

export function ResumeEditor({ resume, onSave }: { resume: Resume; onSave: (patch: Partial<Resume>) => void }) {
  const [title, setTitle] = useState(resume.title); const [summary, setSummary] = useState(resume.summary); const [skills, setSkills] = useState(resume.skills.join(", ")); const [experience, setExperience] = useState(resume.experience.join("\n")); const [error, setError] = useState("");
  return <Card className="p-5"><h1 className="text-2xl font-bold text-ink">Редактирование резюме</h1><p className="mt-2 text-sm leading-6 text-muted">Заполните основные поля. Данные сохраняются в общем demo-state.</p><label className="mt-5 block text-sm font-semibold text-ink">Заголовок<Input className="mt-2" value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="mt-4 block text-sm font-semibold text-ink">О себе<Textarea className="mt-2" value={summary} onChange={(event) => setSummary(event.target.value)} /></label><label className="mt-4 block text-sm font-semibold text-ink">Навыки через запятую<Input className="mt-2" value={skills} onChange={(event) => setSkills(event.target.value)} /></label><label className="mt-4 block text-sm font-semibold text-ink">Опыт — по одному пункту<Textarea className="mt-2" value={experience} onChange={(event) => setExperience(event.target.value)} /></label>{error ? <p className="mt-3 text-sm text-danger" role="alert">{error}</p> : null}<Button className="mt-5 w-full" onClick={() => { if (!title.trim() || !summary.trim()) { setError("Заполните заголовок и описание."); return; } onSave({ title: title.trim(), summary: summary.trim(), skills: skills.split(",").map((item) => item.trim()).filter(Boolean), experience: experience.split("\n").map((item) => item.trim()).filter(Boolean) }); }}>Сохранить резюме</Button></Card>;
}

export function CourseCard({ course, organization, enrolled, favorite, onFavorite }: { course: OpportunityCourse; organization?: Organization; enrolled?: boolean; favorite?: boolean; onFavorite?: (id: string) => void }) {
  return <Card className="p-4"><div className="flex items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2"><Badge>{course.format === "online" ? "Онлайн" : course.format === "hybrid" ? "Гибрид" : "Очно"}</Badge>{course.status === "closed" ? <Badge className="bg-danger/10 text-danger">Набор закрыт</Badge> : enrolled ? <Badge className="text-success">Вы записаны</Badge> : null}</div><Link href={routes.user.course(course.id)} className="mt-3 block"><h3 className="text-lg font-bold text-ink">{course.title}</h3><p className="mt-1 text-sm text-muted">{organization?.name ?? "Провайдер курса"}</p></Link></div><FavoriteButton active={Boolean(favorite)} label={course.title} onClick={() => onFavorite?.(course.id)} /></div><OpportunityMeta><span className="inline-flex items-center gap-1"><Clock3 aria-hidden="true" className="h-4 w-4" />{course.duration}</span><span className="inline-flex items-center gap-1"><GraduationCap aria-hidden="true" className="h-4 w-4" />{course.level}</span></OpportunityMeta><p className="mt-3 text-sm leading-6 text-muted">{course.description}</p><p className="mt-3 text-sm font-semibold text-success">{course.seatsLabel} · {course.schedule}</p><Link href={routes.user.course(course.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть курс</Link></Card>;
}

export function CourseDetail({ course, organization, enrolled, onEnroll, favorite, onFavorite }: { course: OpportunityCourse; organization?: Organization; enrolled: boolean; onEnroll: () => void; favorite: boolean; onFavorite: () => void }) {
  return <div className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge>{course.status === "available" ? "Набор открыт" : "Набор закрыт"}</Badge><h1 className="mt-3 text-2xl font-bold leading-tight text-ink">{course.title}</h1><p className="mt-2 text-sm text-muted">{organization?.name ?? "Провайдер не найден"}</p></div><FavoriteButton active={favorite} label={course.title} onClick={onFavorite} /></div><p className="mt-5 leading-7 text-ink">{course.description}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-control bg-surface-soft p-3"><p className="text-xs text-muted">Формат</p><p className="mt-1 font-semibold text-ink">{course.format === "online" ? "Онлайн" : course.format === "hybrid" ? "Гибрид" : "Очно"}</p></div><div className="rounded-control bg-surface-soft p-3"><p className="text-xs text-muted">Длительность</p><p className="mt-1 font-semibold text-ink">{course.duration}</p></div></div>{enrolled ? <p className="mt-5 rounded-control bg-success/10 p-4 text-sm font-semibold text-success">Вы уже записаны на этот курс.</p> : <Button className="mt-5 w-full" disabled={course.status === "closed"} onClick={onEnroll}>{course.status === "closed" ? "Запись закрыта" : "Записаться на курс"}</Button>}</Card><Card className="p-4"><h2 className="font-bold text-ink">Доступность обучения</h2><ul className="mt-3 grid gap-2 text-sm leading-6 text-ink sm:grid-cols-2">{Object.entries({ "Субтитры": course.accessibility.subtitles, "Расшифровка": course.accessibility.transcript, "Совместим со скринридером": course.accessibility.screenReaderCompatible, "Гибкий темп": course.accessibility.flexiblePace, "Жестовый язык": course.accessibility.signLanguage }).map(([label, value]) => <li key={label} className="flex gap-2"><span className={value ? "text-success" : "text-muted"}>{value ? "✓" : "—"}</span>{label}</li>)}</ul></Card>{organization ? <Link href={routes.user.educationOrganization(organization.id)} className="inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть профиль провайдера</Link> : null}</div>;
}

export function EducationOrganizationCard({ organization, courseCount }: { organization: Organization; courseCount: number }) { return <Card className="p-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-soft text-primary"><GraduationCap aria-hidden="true" className="h-5 w-5" /></span><div><h3 className="font-bold text-ink">{organization.name}</h3><p className="mt-1 text-sm leading-5 text-muted">{organization.description}</p><p className="mt-2 text-sm font-semibold text-success">{courseCount} программы в demo</p></div></div><Link href={routes.user.educationOrganization(organization.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть организацию</Link></Card>; }

export function EventCard({ event, organization, joined, favorite, onFavorite }: { event: OpportunityEvent; organization?: Organization; joined?: boolean; favorite?: boolean; onFavorite?: (id: string) => void }) { return <Card className="p-4"><div className="flex items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2"><Badge>{event.dateLabel}</Badge><Badge className={event.status === "available" ? "text-success" : "text-danger"}>{event.status === "available" ? joined ? "Вы участвуете" : "Есть места" : event.status === "full" ? "Мест нет" : "Завершено"}</Badge></div><Link href={routes.user.event(event.id)} className="mt-3 block"><h3 className="text-lg font-bold text-ink">{event.title}</h3><p className="mt-1 text-sm text-muted">{organization?.name ?? "Организатор события"}</p></Link></div><FavoriteButton active={Boolean(favorite)} label={event.title} onClick={() => onFavorite?.(event.id)} /></div><OpportunityMeta><span className="inline-flex items-center gap-1"><Clock3 aria-hidden="true" className="h-4 w-4" />{event.timeLabel}</span><span className="inline-flex items-center gap-1"><MapPin aria-hidden="true" className="h-4 w-4" />Доступное место</span></OpportunityMeta><p className="mt-3 text-sm leading-6 text-muted">{event.description}</p><Link href={routes.user.event(event.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control bg-primary text-sm font-semibold text-white">Открыть событие</Link></Card>; }

export function EventDetail({ event, organization, place, joined, onJoin, favorite, onFavorite }: { event: OpportunityEvent; organization?: Organization; place?: { id: string; name: string }; joined: boolean; onJoin: () => void; favorite: boolean; onFavorite: () => void }) { return <div className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge>{event.status === "available" ? "Регистрация открыта" : event.status === "full" ? "Всё занято" : "Событие завершено"}</Badge><h1 className="mt-3 text-2xl font-bold leading-tight text-ink">{event.title}</h1><p className="mt-2 text-sm text-muted">{event.dateLabel} · {event.timeLabel}</p></div><FavoriteButton active={favorite} label={event.title} onClick={onFavorite} /></div><p className="mt-5 leading-7 text-ink">{event.description}</p><div className="mt-5 rounded-control bg-surface-soft p-4"><p className="flex gap-2 text-sm font-semibold text-ink"><MapPin aria-hidden="true" className="h-4 w-4 shrink-0 text-primary" />{place?.name ?? "Место события не найдено"}</p>{place ? <Link href={routes.user.place(place.id)} className="mt-2 inline-flex text-sm font-semibold text-primary">Открыть место на карте</Link> : null}</div>{joined ? <p className="mt-5 rounded-control bg-success/10 p-4 text-sm font-semibold text-success">Вы присоединились к событию.</p> : <Button className="mt-5 w-full" disabled={event.status !== "available"} onClick={onJoin}>{event.status === "full" ? "Мест нет" : event.status === "ended" ? "Событие завершено" : "Присоединиться"}</Button>}</Card><Card className="p-4"><h2 className="font-bold text-ink">Условия доступности</h2><ul className="mt-3 space-y-2">{event.accessibilitySummary.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-ink"><Check aria-hidden="true" className="mt-1 h-4 w-4 shrink-0 text-success" />{item}</li>)}</ul></Card>{organization ? <p className="text-sm text-muted">Организатор: {organization.name}</p> : null}</div>; }

export function ClubCard({ club, joined }: { club: Club; joined?: boolean }) { return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><Badge>{club.category}</Badge><Link href={routes.user.club(club.id)} className="mt-3 block"><h3 className="text-lg font-bold text-ink">{club.name}</h3></Link><p className="mt-1 text-sm text-muted">{club.city} · {club.memberCount} участников</p></div><Users aria-hidden="true" className="h-6 w-6 text-primary" /></div><p className="mt-3 text-sm leading-6 text-muted">{club.description}</p><p className="mt-3 text-sm font-semibold text-success">{club.meetingLabel}</p><Link href={routes.user.club(club.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">{joined ? "Открыть клуб" : "Подробнее"}</Link></Card>; }
export function ClubDetail({ club, joined, onJoin }: { club: Club; joined: boolean; onJoin: () => void }) { return <Card className="p-5"><Badge>{club.category}</Badge><h1 className="mt-3 text-2xl font-bold text-ink">{club.name}</h1><p className="mt-2 text-sm text-muted">{club.city} · {club.memberCount} участников</p><p className="mt-5 leading-7 text-ink">{club.description}</p><div className="mt-5 rounded-control bg-surface-soft p-4"><p className="font-semibold text-ink">{club.meetingLabel}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-ink">{club.accessibilitySummary.map((item) => <li key={item}>✓ {item}</li>)}</ul></div>{joined ? <p className="mt-5 rounded-control bg-success/10 p-4 text-sm font-semibold text-success">Вы состоите в этом клубе.</p> : <Button className="mt-5 w-full" onClick={onJoin}>Вступить в клуб</Button>}</Card>; }

export function PartnerOfferCard({ offer, organization, favorite, onFavorite }: { offer: PartnerOffer; organization?: Organization; favorite?: boolean; onFavorite?: (id: string) => void }) { return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div><Badge className={offer.status === "available" ? "text-success" : "text-danger"}>Предложение партнёра · {offer.status === "available" ? "Доступно" : "Завершено"}</Badge><Link href={routes.user.offer(offer.id)} className="mt-3 block"><h3 className="text-lg font-bold text-ink">{offer.title}</h3></Link><p className="mt-1 text-sm text-muted">{organization?.name ?? "Партнёр"}</p></div><FavoriteButton active={Boolean(favorite)} label={offer.title} onClick={() => onFavorite?.(offer.id)} /></div><p className="mt-3 text-sm leading-6 text-muted">{offer.description}</p><p className="mt-3 text-sm font-semibold text-primary">{offer.benefit} · {offer.validUntil}</p><Link href={routes.user.offer(offer.id)} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть предложение</Link></Card>; }
export function PartnerOfferDetail({ offer, organization, favorite, onFavorite }: { offer: PartnerOffer; organization?: Organization; favorite: boolean; onFavorite: () => void }) { return <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge className={offer.status === "available" ? "text-success" : "text-danger"}>Предложение партнёра · {offer.status === "available" ? "Предложение действует" : "Срок завершён"}</Badge><h1 className="mt-3 text-2xl font-bold text-ink">{offer.title}</h1></div><FavoriteButton active={favorite} label={offer.title} onClick={onFavorite} /></div><p className="mt-5 leading-7 text-ink">{offer.description}</p><p className="mt-5 rounded-control bg-primary-soft p-4 font-bold text-primary">{offer.benefit}</p><p className="mt-4 text-sm text-muted">Партнёр: {organization?.name ?? "Профиль не найден"}. Срок: {offer.validUntil}.</p><Button className="mt-5 w-full" disabled={offer.status === "expired"}>{offer.status === "expired" ? "Предложение недоступно" : "Получить предложение"}</Button></Card>; }

export function MissingOpportunity({ title = "Объект не найден", backHref = routes.user.opportunities }: { title?: string; backHref?: string }) { return <EmptyState title={title} description="Проверьте ссылку или вернитесь к списку возможностей." action={<Link href={backHref} className="inline-flex min-h-11 items-center gap-2 rounded-control bg-primary px-4 text-sm font-semibold text-white"><ArrowLeft aria-hidden="true" className="h-4 w-4" />Вернуться</Link>} />; }
