"use client";

import { CheckCircle2, Clock3, MapPin, Navigation, ShieldCheck, SlidersHorizontal, Timer, Users } from "lucide-react";
import type { HelpRequest, Place } from "@/types";
import Link from "next/link";
import { routes } from "@/lib/routes";
import { cn } from "@/lib/cn";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Avatar } from "@/components/ui/Avatar";
import { Input } from "@/components/ui/Input";
import { MapCanvas } from "@/components/map/MapCanvas";
import { Timeline } from "@/components/help/HelpComponents";
import type { HelpRequestMeta, VolunteerProfileDetails } from "@/types/volunteer";

export function VolunteerSummary({ available, onToggle, activeCount, matchingCount }: { available: boolean; onToggle: () => void; activeCount: number; matchingCount: number }) {
  return <Card className="border-primary/20 bg-primary-soft p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[0.08em] text-primary">Кабинет волонтёра</p><h1 className="mt-2 text-2xl font-bold text-ink">Помощь рядом</h1><p className="mt-2 text-sm leading-6 text-muted">{matchingCount} подходящих заявки · {activeCount} активной помощи</p></div><button type="button" onClick={onToggle} aria-pressed={available} className={cn("min-h-11 min-w-[5.5rem] shrink-0 rounded-full px-3 py-2 text-center text-xs font-bold leading-tight", available ? "bg-success text-white" : "border border-border bg-surface text-muted")}>{available ? "Я доступен" : "Недоступен"}</button></div><p className="mt-4 text-sm text-ink"><span className={cn("mr-2 inline-block h-2.5 w-2.5 rounded-full", available ? "bg-success" : "bg-muted")} aria-hidden="true" />{available ? "Получайте подходящие заявки" : "Новые заявки временно приостановлены"}</p></Card>;
}

export function ImpactSummary({ completedCount }: { completedCount: number }) {
  return <Card className="p-4"><div className="flex items-center gap-2"><Users aria-hidden="true" className="h-5 w-5 text-primary" /><h2 className="font-bold text-ink">Ваш вклад</h2></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div><p className="text-xl font-bold text-primary">{completedCount}</p><p className="text-xs text-muted">завершено</p></div><div><p className="text-xl font-bold text-primary">4,9</p><p className="text-xs text-muted">оценка демонстрации</p></div><div><p className="text-xl font-bold text-primary">8 км</p><p className="text-xs text-muted">радиус</p></div></div></Card>;
}

export function HelpRequestCard({ request, meta, onOpen, onAccept }: { request: HelpRequest; meta: HelpRequestMeta; onOpen: () => void; onAccept?: () => void }) {
  const assigned = Boolean(request.volunteerId);
  return <Card className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge>{meta.kindLabel}</Badge><Badge><MapPin aria-hidden="true" className="h-3.5 w-3.5" />{meta.distanceKm} км</Badge></div><h2 className="mt-3 font-bold text-ink">{request.title}</h2></div>{assigned ? <Badge className="text-warning">Уже принята</Badge> : null}</div><p className="mt-2 text-sm leading-5 text-muted">{request.dateLabel} · {request.estimatedDuration ?? "Время уточняется"}</p><p className="mt-2 text-sm text-ink">{request.approximateArea ?? "Район уточняется"} · {request.locationLabel}</p><p className="mt-3 rounded-control bg-surface-soft p-3 text-sm leading-5 text-muted">До принятия точные контакты и место встречи скрыты. Нужны навыки: {meta.neededSkills.join(", ")}.</p><div className="mt-4 flex gap-2"><Button variant="secondary" className="flex-1" onClick={onOpen}>Подробнее</Button>{onAccept ? <Button className="flex-1" disabled={assigned} onClick={onAccept}>{assigned ? "Уже принята" : "Откликнуться"}</Button> : null}</div></Card>;
}

export function RequestFilters({ query, onQuery, kind, onKind, maxDistance, onDistance }: { query: string; onQuery: (value: string) => void; kind: string; onKind: (value: string) => void; maxDistance: string; onDistance: (value: string) => void }) {
  return <Card className="p-4"><div className="flex items-center gap-2"><SlidersHorizontal aria-hidden="true" className="h-5 w-5 text-primary" /><h2 className="font-bold text-ink">Фильтры</h2></div><div className="mt-3 space-y-3"><label className="block text-sm font-semibold text-ink">Поиск по задаче<Input value={query} onChange={(event) => onQuery(event.target.value)} className="mt-1" placeholder="Клиника, документы…" /></label><div className="grid grid-cols-2 gap-2"><label className="text-sm font-semibold text-ink">Тип<select value={kind} onChange={(event) => onKind(event.target.value)} className="mt-1 min-h-12 w-full rounded-control border border-border bg-surface px-3 text-sm text-ink"><option value="all">Все задачи</option><option value="clinic">Клиника</option><option value="documents">Документы</option><option value="event">Мероприятие</option><option value="station">Вокзал</option><option value="medicine">Лекарства</option><option value="household">Быт</option><option value="trip">Поездка</option></select></label><label className="text-sm font-semibold text-ink">Радиус<select value={maxDistance} onChange={(event) => onDistance(event.target.value)} className="mt-1 min-h-12 w-full rounded-control border border-border bg-surface px-3 text-sm text-ink"><option value="15">До 15 км</option><option value="5">До 5 км</option><option value="3">До 3 км</option></select></label></div></div></Card>;
}

export function HelpRequestDetail({ request, meta, canAccept, acceptedByOther, onAccept, onCancel }: { request: HelpRequest; meta: HelpRequestMeta; canAccept: boolean; acceptedByOther: boolean; onAccept: () => void; onCancel?: () => void }) {
  const accepted = request.status === "accepted" || request.status === "volunteer_on_way" || request.status === "active" || request.status === "completed";
  const visibleDescription = request.description?.replace(/\s*Контакты:.*$/i, "").trim();
  return <div className="space-y-4"><Card className="p-5"><div className="flex flex-wrap items-center gap-2"><Badge>{meta.kindLabel}</Badge><Badge><Clock3 aria-hidden="true" className="h-3.5 w-3.5" />{request.dateLabel}</Badge></div><h1 className="mt-4 text-2xl font-bold text-ink">{request.title}</h1>{visibleDescription ? <p className="mt-3 text-sm leading-6 text-muted">{visibleDescription}</p> : null}<div className="mt-5 space-y-3 text-sm leading-6 text-ink"><p><strong>Район:</strong> {request.approximateArea ?? "Уточняется"}</p><p><strong>Маршрут:</strong> {accepted ? meta.exactLocationLabel : request.locationLabel}</p><p><strong>Длительность:</strong> {request.estimatedDuration ?? "Уточняется"}</p><p><strong>Нужны навыки:</strong> {meta.neededSkills.join(", ")}</p></div>{meta.destinationPlaceId ? <Link href={routes.user.place(meta.destinationPlaceId)} className="mt-4 flex min-h-11 items-center justify-center rounded-control border border-primary/30 bg-primary-soft px-3 text-sm font-semibold text-primary"><MapPin aria-hidden="true" className="mr-2 h-4 w-4" />Открыть связанное место на карте</Link> : null}{!accepted ? <p className="mt-4 rounded-control border border-warning/30 bg-warning/5 p-3 text-sm leading-5 text-ink">Приватность до принятия: точная точка встречи и контакты участника появятся только после отклика.</p> : <div className="mt-4 rounded-control border border-success/30 bg-success/5 p-3 text-sm leading-5 text-ink"><strong>Контакты:</strong> {meta.contactLabel}</div>}{acceptedByOther ? <Button className="mt-5 w-full" disabled>Эта заявка уже принята</Button> : canAccept ? <Button className="mt-5 w-full" onClick={onAccept}>Откликнуться помочь</Button> : null}{onCancel ? <Button variant="secondary" className="mt-2 w-full" onClick={onCancel}>Отказаться до начала помощи</Button> : null}</Card><Card className="p-4"><h2 className="font-bold text-ink">Что важно учесть</h2><ul className="mt-3 space-y-2 text-sm leading-5 text-muted">{meta.accessibilityNotes.map((note) => <li key={note} className="flex gap-2"><CheckCircle2 aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-success" />{note}</li>)}</ul></Card></div>;
}

export function HelpStatusTimeline({ status }: { status: HelpRequest["status"] }) {
  const sequence: HelpRequest["status"][] = ["accepted", "volunteer_on_way", "active", "completed"];
  const labels: Record<string, string> = { accepted: "Заявка принята", volunteer_on_way: "Я в пути", active: "Помощь началась", completed: "Помощь завершена" };
  const index = sequence.indexOf(status);
  return <Timeline items={sequence.map((item, itemIndex) => ({ label: labels[item], detail: itemIndex <= index ? "Шаг пройден" : "Следующий шаг", current: item === status }))} />;
}

export function ActiveHelpCard({ request, meta, onAction, actionLabel, onCancel, timerLabel }: { request: HelpRequest; meta: HelpRequestMeta; onAction?: () => void; actionLabel?: string; onCancel?: () => void; timerLabel?: string }) {
  return <div className="space-y-4"><Card className="border-primary/20 bg-primary-soft p-5"><div className="flex items-center gap-2 text-primary"><Navigation aria-hidden="true" className="h-5 w-5" /><span className="text-sm font-semibold">Активная помощь</span></div><h1 className="mt-3 text-xl font-bold text-ink">{request.title}</h1><p className="mt-2 text-sm text-muted">{meta.exactLocationLabel} · {meta.etaLabel}</p>{timerLabel ? <p className="mt-3 flex items-center gap-2 text-sm font-bold text-primary"><Timer aria-hidden="true" className="h-4 w-4" />{timerLabel}</p> : null}{onAction ? <Button className="mt-5 w-full" onClick={onAction}>{actionLabel}</Button> : null}{onCancel ? <Button variant="secondary" className="mt-2 w-full" onClick={onCancel}>Отказаться до начала помощи</Button> : null}</Card><Card className="p-4"><h2 className="font-bold text-ink">Контакты и заметки</h2><p className="mt-2 text-sm leading-6 text-ink">{meta.contactLabel}</p><p className="mt-3 text-sm leading-6 text-muted">{meta.accessibilityNotes.join(" · ")}</p><h3 className="mt-4 text-sm font-bold text-ink">Чек-лист</h3><ul className="mt-2 space-y-2 text-sm text-muted">{meta.checklist.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 aria-hidden="true" className="h-4 w-4 shrink-0 text-success" />{item}</li>)}</ul></Card></div>;
}

export function VolunteerProfileCard({ profile, completedCount, onToggle, onRadius, onSkillToggle, onLanguageToggle }: { profile: VolunteerProfileDetails; completedCount: number; onToggle: () => void; onRadius: (value: number) => void; onSkillToggle: (skill: string) => void; onLanguageToggle: (language: string) => void }) {
  const languages = ["Русский", "Английский", "Татарский", "Жестовый язык"];
  return <div className="space-y-4"><Card className="p-5"><div className="flex items-start gap-3"><Avatar initials={profile.initials} className="h-14 w-14 text-base" /><div className="min-w-0"><h1 className="text-xl font-bold text-ink">{profile.displayName}</h1><p className="mt-1 text-sm text-muted">{profile.city}</p>{profile.verified ? <Badge className="mt-2 text-success"><ShieldCheck aria-hidden="true" className="h-3.5 w-3.5" />Проверенный волонтёр</Badge> : null}</div></div><div className="mt-5 flex items-center justify-between rounded-control bg-surface-soft p-3"><span className="text-sm font-semibold text-ink">Принимать заявки</span><button type="button" onClick={onToggle} aria-pressed={profile.available} className={cn("min-h-11 rounded-full px-3 text-xs font-bold", profile.available ? "bg-success text-white" : "bg-surface border border-border text-muted")}>{profile.available ? "Включено" : "Выключено"}</button></div><div className="mt-4"><label className="text-sm font-semibold text-ink">Радиус помощи: {profile.radiusKm} км<input type="range" min="1" max="20" value={profile.radiusKm} onChange={(event) => onRadius(Number(event.target.value))} className="mt-3 w-full accent-primary" /></label></div></Card><Card className="p-4"><h2 className="font-bold text-ink">Навыки и языки</h2><p className="mt-3 text-sm font-semibold text-ink">Навыки</p><div className="mt-2 flex flex-wrap gap-2">{profile.skills.map((skill) => <button type="button" key={skill} onClick={() => onSkillToggle(skill)} className="min-h-10 rounded-full border border-primary/30 bg-primary-soft px-3 text-sm font-semibold text-primary" aria-pressed="true">{skill}</button>)}</div><p className="mt-4 text-sm font-semibold text-ink">Языки</p><div className="mt-2 flex flex-wrap gap-2">{languages.map((language) => <button type="button" key={language} onClick={() => onLanguageToggle(language)} className={cn("min-h-10 rounded-full border px-3 text-sm font-semibold", profile.languages.includes(language) ? "border-primary bg-primary-soft text-primary" : "border-border text-muted")} aria-pressed={profile.languages.includes(language)}>{language}</button>)}</div></Card><ImpactSummary completedCount={completedCount} /></div>;
}

export function VolunteerMap({ requests, onSelect }: { requests: { request: HelpRequest; meta: HelpRequestMeta }[]; onSelect: (id: string) => void }) {
  const mapPlaces: Place[] = requests.map(({ request }, index) => ({ id: request.id, name: request.title, category: "help", address: request.approximateArea ?? "Москва", coordinates: { lat: 55.74 + (index % 5) * 0.009, lng: 37.59 + (index % 4) * 0.018 }, schedule: request.dateLabel, verified: true, verificationSource: "community", lastConfirmedLabel: "Тестовая заявка", accessibility: { stepFree: true, ramp: "unknown", elevator: "unknown", accessibleToilet: "unknown", wideDoors: "unknown", accessibleParking: "unknown", tactileNavigation: "unknown", hearingLoop: "unknown", quietZone: "unknown", assistanceAvailable: true }, images: [] }));
  return <div className="space-y-3"><MapCanvas places={mapPlaces} selectedPlaceId={null} onSelect={onSelect} /><div className="rounded-control bg-surface-soft p-3 text-sm text-muted">Маркеры показывают заявки рядом, а не места. Точные данные открываются после принятия.</div></div>;
}

export function OnboardingStep({ step, title, children }: { step: number; title: string; children: React.ReactNode }) { return <Card className="p-5"><p className="text-sm font-semibold text-primary">Шаг {step} из 6</p><h1 className="mt-2 text-2xl font-bold text-ink">{title}</h1><div className="mt-5">{children}</div></Card>; }
