"use client";

import { ArrowLeft, ArrowRight, BadgeCheck, CalendarDays, Heart, Link2, MapPin, MessageCircle, MoreHorizontal, Send, Share2, Users, X } from "lucide-react";
import Link from "next/link";
import { createPortal } from "react-dom";
import { useEffect, useRef } from "react";
import type { SocialCommunity, SocialPost, SocialStory, SocialUser } from "@/types/social";
import { routes } from "@/lib/routes";
import { cn } from "@/lib/cn";
import { Avatar } from "@/components/ui/Avatar";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { IconButton } from "@/components/ui/IconButton";
import { VerifiedBadge } from "@/components/demo/VerifiedBadge";
import { useDemoPhoneOverlay } from "@/components/demo/DemoPhoneOverlayRoot";

export type SocialAuthor = { id: string; name: string; verified: boolean; city?: string; avatarLabel: string; authorType: "user" | "organization"; };

export function SocialTabs({ active, onChange }: { active: "community" | "popular" | "following"; onChange: (tab: "community" | "popular" | "following") => void }) {
  const tabs = [{ id: "community", label: "Моё сообщество" }, { id: "popular", label: "Популярное" }, { id: "following", label: "Подписки" }] as const;
  return <div role="tablist" aria-label="Фильтр ленты" className="grid grid-cols-3 rounded-control bg-surface-soft p-1">{tabs.map((tab) => <button key={tab.id} type="button" role="tab" aria-selected={active === tab.id} onClick={() => onChange(tab.id)} className={cn("min-h-11 rounded-control px-2 text-xs font-semibold", active === tab.id ? "bg-surface text-primary shadow-sm" : "text-muted hover:text-ink")}>{tab.label}</button>)}</div>;
}

export function StoryRail({ stories, authors, onOpen }: { stories: SocialStory[]; authors: Record<string, SocialAuthor>; onOpen: (storyId: string) => void }) {
  return <section aria-labelledby="stories-title"><div className="flex items-center justify-between"><h2 id="stories-title" className="text-lg font-bold text-ink">Короткие обновления</h2><Badge>{stories.length}</Badge></div><div className="mt-3 flex gap-3 overflow-x-auto pb-2" role="list">{stories.map((story) => { const author = authors[story.authorId]; return <button key={story.id} type="button" onClick={() => onOpen(story.id)} className="flex w-20 shrink-0 flex-col items-center gap-2 rounded-control p-1 text-center focus:outline-none focus:ring-2 focus:ring-focus"><span className="rounded-full bg-gradient-to-br from-primary to-violet p-0.5"><Avatar initials={author?.avatarLabel ?? "?"} className="h-14 w-14 border-2 border-surface" /></span><span className="line-clamp-2 text-xs font-semibold text-ink">{story.title}</span></button>; })}</div></section>;
}

export function StoryViewer({ story, author, onClose, onNext, onPrevious, reducedMotion }: { story: SocialStory; author: SocialAuthor; onClose: () => void; onNext: () => void; onPrevious: () => void; reducedMotion: boolean }) {
  const overlayRoot = useDemoPhoneOverlay();
  const closeRef = useRef<HTMLButtonElement>(null); const previousFocus = useRef<HTMLElement | null>(null);
  useEffect(() => { previousFocus.current = document.activeElement as HTMLElement; closeRef.current?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); if (event.key === "ArrowRight") onNext(); if (event.key === "ArrowLeft") onPrevious(); }; document.addEventListener("keydown", handleKey); return () => { document.removeEventListener("keydown", handleKey); previousFocus.current?.focus(); }; }, [onClose, onNext, onPrevious]);
  const viewer = <div className={cn(overlayRoot ? "absolute" : "fixed", "pointer-events-auto inset-0 z-50 flex items-center justify-center bg-surface-inverse/80 p-4")} role="dialog" aria-modal="true" aria-label={`История: ${story.title}`}><div className={cn("relative w-full max-w-md overflow-y-auto rounded-card bg-surface p-5 shadow-device", !reducedMotion && "transition-transform") }><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Avatar initials={author.avatarLabel} /><div className="min-w-0"><p className="truncate font-bold text-ink">{author.name}</p><p className="text-xs text-muted">{story.dateLabel}</p></div></div><button ref={closeRef} type="button" aria-label="Закрыть историю" onClick={onClose} className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-control border border-border bg-surface text-ink hover:bg-surface-soft"><X aria-hidden="true" className="h-5 w-5" /></button></div><div className="mt-10 min-h-48 rounded-card bg-gradient-to-br from-primary-soft via-surface to-ai-soft p-5"><Badge>{story.type === "event" ? "Событие" : story.type === "course" ? "Курс" : story.type === "volunteer" ? "Волонтёры" : story.type === "update" ? "Место" : "Совет"}</Badge><h1 className="mt-5 text-2xl font-bold leading-tight text-ink">{story.title}</h1><p className="mt-3 text-base leading-7 text-ink">{story.body}</p></div><div className="mt-5 grid gap-2 min-[380px]:grid-cols-3"><Button className="w-full" variant="secondary" onClick={onPrevious}><ArrowLeft aria-hidden="true" className="h-4 w-4" />Назад</Button>{story.ctaHref ? <Link href={story.ctaHref} className="inline-flex min-h-11 w-full items-center justify-center rounded-control bg-primary px-4 text-sm font-semibold text-white">{story.ctaLabel ?? "Открыть"}</Link> : null}<Button className="w-full" variant="secondary" onClick={onNext}>Далее<ArrowRight aria-hidden="true" className="h-4 w-4" /></Button></div><p className="mt-4 text-center text-xs text-muted">Используйте ← → или Esc</p></div></div>;
  return overlayRoot ? createPortal(viewer, overlayRoot) : viewer;
}

export function AuthorHeader({ author, following, onFollow, onOpenProfile }: { author: SocialAuthor; following?: boolean; onFollow?: () => void; onOpenProfile?: () => void }) {
  return <div className="flex items-start gap-3"><button type="button" onClick={onOpenProfile} className="rounded-full focus:outline-none focus:ring-2 focus:ring-focus" aria-label={`Открыть профиль ${author.name}`}><Avatar initials={author.avatarLabel} /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={onOpenProfile} className="font-bold text-ink hover:text-primary">{author.name}</button>{author.verified ? <VerifiedBadge label="Профиль проверен" /> : null}</div>{author.city ? <p className="mt-1 text-xs text-muted">{author.city}</p> : null}</div>{onFollow ? <Button size="sm" variant={following ? "secondary" : "primary"} onClick={onFollow}>{following ? "Подписка" : "Подписаться"}</Button> : null}</div>;
}

export function ReactionBar({ post, liked, saved, onReact, onSave, onShare, onComment }: { post: SocialPost; liked: boolean; saved: boolean; onReact: () => void; onSave: () => void; onShare: () => void; onComment?: () => void }) {
  return <div className="mt-4 flex flex-wrap items-center gap-1 border-t border-border pt-3"><button type="button" aria-label={liked ? "Убрать реакцию" : "Поставить реакцию"} aria-pressed={liked} onClick={onReact} className={cn("inline-flex min-h-11 items-center gap-1 rounded-control px-3 text-sm font-semibold", liked ? "bg-danger/10 text-danger" : "text-muted hover:bg-surface-soft")}><Heart aria-hidden="true" className={cn("h-5 w-5", liked && "fill-danger")} />{post.reactions + (liked ? 1 : 0)}</button><button type="button" aria-label={saved ? "Убрать публикацию из сохранённых" : "Сохранить публикацию"} aria-pressed={saved} onClick={onSave} className={cn("inline-flex min-h-11 items-center gap-1 rounded-control px-3 text-sm font-semibold", saved ? "bg-primary-soft text-primary" : "text-muted hover:bg-surface-soft")}><BookmarkIcon active={saved} />Сохранить</button><button type="button" aria-label="Поделиться публикацией" onClick={onShare} className="inline-flex min-h-11 items-center gap-1 rounded-control px-3 text-sm font-semibold text-muted hover:bg-surface-soft"><Share2 aria-hidden="true" className="h-5 w-5" />Поделиться</button><button type="button" aria-label={`${post.commentCount} комментариев`} onClick={onComment} className="inline-flex min-h-11 items-center gap-1 rounded-control px-3 text-sm font-semibold text-muted hover:bg-surface-soft"><MessageCircle aria-hidden="true" className="h-5 w-5" />{post.commentCount}</button></div>;
}
function BookmarkIcon({ active }: { active: boolean }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className={cn("h-5 w-5", active && "fill-primary")} fill="none" stroke="currentColor" strokeWidth="2"><path d="M6 4.5A2.5 2.5 0 0 1 8.5 2h7A2.5 2.5 0 0 1 18 4.5V21l-6-3-6 3Z" /></svg>; }

export function PostCard({ post, author, liked, saved, followingAuthor, simpleMode, onOpen, onReact, onSave, onShare, onFollow, onOpenProfile }: { post: SocialPost; author: SocialAuthor; liked: boolean; saved: boolean; followingAuthor: boolean; simpleMode?: boolean; onOpen: () => void; onReact: () => void; onSave: () => void; onShare: () => void; onFollow: () => void; onOpenProfile: () => void }) {
  return <Card className="p-4"><AuthorHeader author={author} following={followingAuthor} onFollow={onFollow} onOpenProfile={onOpenProfile} /><button type="button" onClick={onOpen} className="mt-4 block w-full text-left focus:outline-none focus:ring-2 focus:ring-focus"><div className="flex flex-wrap gap-2"><Badge>{post.type === "accessibility_update" ? "Обновление места" : post.type === "job_tip" ? "Совет о работе" : post.type === "useful_guide" ? "Полезный совет" : post.type === "community_invite" ? "Приглашение" : post.type === "organization" ? "Организация" : post.type === "course" ? "Курс" : post.type === "event" ? "Событие" : post.type === "volunteer_call" ? "Волонтёры" : "Опыт пользователя"}</Badge><span className="text-xs text-muted">{post.dateLabel}</span></div><h2 className="mt-3 text-lg font-bold leading-6 text-ink">{post.title}</h2><p className={cn("mt-2 text-sm leading-6 text-muted", simpleMode && "line-clamp-2")}>{post.body}</p>{!simpleMode && post.tags.length ? <div className="mt-3 flex flex-wrap gap-2">{post.tags.map((tag) => <Badge key={tag}>#{tag}</Badge>)}</div> : null}</button><ReactionBar post={post} liked={liked} saved={saved} onReact={onReact} onSave={onSave} onShare={onShare} /></Card>;
}

export function PostDetail({ post, author, liked, saved, following, simpleMode, related, comments, onReact, onSave, onShare, onFollow, onOpenProfile, onReport }: { post: SocialPost; author: SocialAuthor; liked: boolean; saved: boolean; following: boolean; simpleMode?: boolean; related?: { label: string; href: string; icon?: "map" | "event" | "course" | "help" | "club" }; comments: string[]; onReact: () => void; onSave: () => void; onShare: () => void; onFollow: () => void; onOpenProfile: () => void; onReport: () => void }) {
  return <div className="space-y-4"><Card className="p-5"><AuthorHeader author={author} following={following} onFollow={onFollow} onOpenProfile={onOpenProfile} /><div className="mt-5 flex flex-wrap gap-2"><Badge>{post.type === "accessibility_update" ? "Обновление места" : post.type === "course" ? "Курс" : post.type === "event" ? "Событие" : "Публикация"}</Badge><span className="text-sm text-muted">{post.dateLabel}</span></div><h1 className="mt-3 text-2xl font-bold leading-tight text-ink">{post.title}</h1><p className={cn("mt-4 whitespace-pre-line text-base leading-7 text-ink", simpleMode && "text-lg leading-8")}>{post.body}</p>{post.media?.length ? <div className="mt-5 grid gap-3 sm:grid-cols-2">{post.media.map((media) => <div key={media} className="flex min-h-28 items-center justify-center rounded-card bg-surface-soft text-sm text-muted" role="img" aria-label={`Изображение публикации: ${media}`}>Изображение demo</div>)}</div> : null}<ReactionBar post={post} liked={liked} saved={saved} onReact={onReact} onSave={onSave} onShare={onShare} /><div className="mt-3 flex flex-wrap justify-between gap-2"><button type="button" onClick={onReport} className="min-h-11 text-sm font-semibold text-muted hover:text-danger">Сообщить о публикации</button><button type="button" onClick={onShare} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary"><Link2 aria-hidden="true" className="h-4 w-4" />Скопировать ссылку</button></div></Card>{related ? <Card className="p-4"><p className="text-sm font-semibold text-muted">Связано с публикацией</p><Link href={related.href} className="mt-2 flex min-h-12 items-center justify-between rounded-control bg-primary-soft px-3 text-sm font-semibold text-primary">{related.icon === "map" ? <MapPin aria-hidden="true" className="mr-2 h-4 w-4" /> : related.icon === "event" ? <CalendarDays aria-hidden="true" className="mr-2 h-4 w-4" /> : related.icon === "course" ? <BadgeCheck aria-hidden="true" className="mr-2 h-4 w-4" /> : related.icon === "help" ? <Send aria-hidden="true" className="mr-2 h-4 w-4" /> : <Users aria-hidden="true" className="mr-2 h-4 w-4" />}{related.label}<ArrowRight aria-hidden="true" className="ml-auto h-4 w-4" /></Link></Card> : null}<Card className="p-4"><div className="flex items-center justify-between"><h2 className="font-bold text-ink">Комментарии</h2><Badge>{post.commentCount}</Badge></div>{comments.length ? <div className="mt-3 space-y-3">{comments.map((comment) => <p key={comment} className="rounded-control bg-surface-soft p-3 text-sm leading-6 text-ink">{comment}</p>)}</div> : <p className="mt-3 text-sm text-muted">Комментарии появятся после первого ответа.</p>}</Card></div>;
}

export function CommunityCard({ community, joined, onJoin }: { community: SocialCommunity; joined: boolean; onJoin: () => void }) { return <Card className="p-4"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-primary-soft text-primary"><Users aria-hidden="true" className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link href={routes.user.communityDetail(community.id)} className="font-bold text-ink">{community.title}</Link>{community.verified ? <VerifiedBadge /> : null}</div><p className="mt-1 text-sm text-muted">{community.city} · {community.memberCount} участников</p></div></div><p className="mt-3 text-sm leading-6 text-muted">{community.description}</p><div className="mt-3 flex flex-wrap gap-2">{community.tags.slice(0, 3).map((tag) => <Badge key={tag}>#{tag}</Badge>)}</div><div className="mt-4 flex gap-2"><Link href={routes.user.communityDetail(community.id)} className="inline-flex min-h-11 flex-1 items-center justify-center rounded-control border border-border bg-surface text-sm font-semibold text-ink">Открыть</Link><Button size="sm" variant={joined ? "secondary" : "primary"} className="flex-1" onClick={onJoin}>{joined ? "Вы участник" : "Вступить"}</Button></div></Card>; }

export function CommunityDetail({ community, joined, moderators, posts, events, onJoin }: { community: SocialCommunity; joined: boolean; moderators: SocialAuthor[]; posts: SocialPost[]; events: { id: string; title: string; href: string; dateLabel: string }[]; onJoin: () => void }) { return <div className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge>{community.verified ? "Проверенное сообщество" : "Сообщество"}</Badge><h1 className="mt-3 text-2xl font-bold text-ink">{community.title}</h1><p className="mt-2 text-sm text-muted">{community.city} · {community.memberCount} участников</p></div><Users aria-hidden="true" className="h-7 w-7 text-primary" /></div><p className="mt-5 leading-7 text-ink">{community.description}</p><div className="mt-4 flex flex-wrap gap-2">{community.tags.map((tag) => <Badge key={tag}>#{tag}</Badge>)}</div>{joined ? <p className="mt-5 rounded-control bg-success/10 p-4 text-sm font-semibold text-success">Вы участник этого сообщества.</p> : <Button className="mt-5 w-full" onClick={onJoin}>Вступить в сообщество</Button>}</Card><Card className="p-4"><h2 className="font-bold text-ink">Модераторы</h2><div className="mt-3 space-y-3">{moderators.map((moderator) => <AuthorHeader key={moderator.id} author={moderator} onOpenProfile={() => undefined} />)}</div></Card><Card className="p-4"><h2 className="font-bold text-ink">Ближайшие события</h2>{events.length ? <div className="mt-3 space-y-2">{events.map((event) => <Link key={event.id} href={event.href} className="flex min-h-12 items-center justify-between rounded-control border border-border px-3 text-sm font-semibold text-ink"><span><CalendarDays aria-hidden="true" className="mr-2 inline h-4 w-4 text-primary" />{event.title}<span className="ml-2 text-xs font-normal text-muted">{event.dateLabel}</span></span><ArrowRight aria-hidden="true" className="h-4 w-4 text-muted" /></Link>)}</div> : <p className="mt-3 text-sm text-muted">Ближайших событий пока нет.</p>}</Card><div><h2 className="text-xl font-bold text-ink">Публикации сообщества</h2><div className="mt-3 space-y-3">{posts.map((post) => <Card key={post.id} className="p-4"><p className="text-sm font-bold text-ink">{post.title}</p><p className="mt-2 text-sm leading-6 text-muted">{post.body}</p><Link href={routes.user.post(post.id)} className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-primary">Открыть публикацию</Link></Card>)}</div></div></div>; }

export function UserCard({ user, state, onAdd, onOpen }: { user: SocialUser; state: "friend" | "incoming" | "outgoing" | "none"; onAdd?: () => void; onOpen: () => void }) { return <Card className="p-4"><div className="flex items-start gap-3"><button type="button" onClick={onOpen} aria-label={`Открыть профиль ${user.name}`}><Avatar initials={user.avatarLabel} /></button><div className="min-w-0 flex-1"><button type="button" onClick={onOpen} className="font-bold text-ink">{user.name}</button>{user.verified ? <div className="mt-1"><VerifiedBadge /></div> : null}<p className="mt-1 text-sm text-muted">{user.city} · {user.interests.slice(0, 2).join(" · ")}</p></div></div>{onAdd ? <Button size="sm" variant={state === "friend" ? "secondary" : "primary"} className="mt-4 w-full" onClick={onAdd} disabled={state !== "none"}>{state === "friend" ? "Вы друзья" : state === "outgoing" ? "Заявка отправлена" : state === "incoming" ? "Есть входящая заявка" : "Добавить в друзья"}</Button> : null}</Card>; }

export function UserProfile({ user, communities, posts, mutualFriends, friendState, following, onAddFriend, onFollow, onContact, onReport }: { user: SocialUser; communities: SocialCommunity[]; posts: SocialPost[]; mutualFriends: SocialUser[]; friendState: "friend" | "incoming" | "outgoing" | "none"; following: boolean; contactRequested: boolean; onAddFriend: () => void; onFollow: () => void; onContact: () => void; onReport: () => void }) { void onContact; return <div className="space-y-4"><Card className="p-5"><div className="flex items-start gap-3"><Avatar initials={user.avatarLabel} className="h-16 w-16 text-base" /><div><h1 className="text-2xl font-bold text-ink">{user.name}</h1>{user.verified ? <div className="mt-2"><VerifiedBadge label="Профиль проверен" /></div> : null}<p className="mt-2 text-sm text-muted">{user.ageLabel} · {user.city}</p></div></div><p className="mt-5 leading-7 text-ink">{user.bio}</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><Button variant={friendState === "friend" ? "secondary" : "primary"} onClick={onAddFriend} disabled={friendState !== "none"}>{friendState === "friend" ? "Вы друзья" : friendState === "outgoing" ? "Заявка отправлена" : friendState === "incoming" ? "Есть входящая заявка" : "Добавить в друзья"}</Button><Button variant={following ? "secondary" : "primary"} onClick={onFollow}>{following ? "Вы подписаны" : "Подписаться"}</Button></div><button type="button" onClick={onReport} className="mt-4 min-h-11 text-sm font-semibold text-muted hover:text-danger">Сообщить о пользователе</button></Card>{mutualFriends.length ? <MutualFriends users={mutualFriends} /> : null}<Card className="p-4"><h2 className="font-bold text-ink">Сообщества</h2><div className="mt-3 flex flex-wrap gap-2">{communities.map((community) => <Link key={community.id} href={routes.user.communityDetail(community.id)} className="rounded-full bg-primary-soft px-3 py-2 text-sm font-semibold text-primary">{community.title}</Link>)}</div></Card><section><h2 className="text-xl font-bold text-ink">Публикации</h2>{posts.length ? <div className="mt-3 space-y-3">{posts.map((post) => <Link key={post.id} href={routes.user.post(post.id)} className="block"><Card className="p-4"><p className="font-bold text-ink">{post.title}</p><p className="mt-2 text-sm leading-6 text-muted">{post.body}</p></Card></Link>)}</div> : <Card className="mt-3 border-dashed p-4 text-sm text-muted">Публикаций пока нет.</Card>}</section></div>; }

export function MutualFriends({ users }: { users: SocialUser[] }) { return <Card className="p-4"><h2 className="font-bold text-ink">Общие друзья</h2><div className="mt-3 flex flex-wrap gap-3">{users.map((user) => <span key={user.id} className="flex items-center gap-2 text-sm text-ink"><Avatar initials={user.avatarLabel} className="h-8 w-8 text-xs" />{user.name}</span>)}</div></Card>; }

export function FriendRequestCard({ user, direction, onAccept, onDecline }: { user: SocialUser; direction: "incoming" | "outgoing"; onAccept?: () => void; onDecline?: () => void }) { return <Card className="p-4"><div className="flex items-center gap-3"><Avatar initials={user.avatarLabel} /><div><p className="font-bold text-ink">{user.name}</p><p className="text-sm text-muted">{direction === "incoming" ? "Хочет добавить вас в друзья" : "Заявка ожидает ответа"}</p></div></div>{direction === "incoming" ? <div className="mt-4 flex gap-2"><Button size="sm" className="flex-1" onClick={onAccept}>Принять</Button><Button size="sm" variant="secondary" className="flex-1" onClick={onDecline}>Отклонить</Button></div> : <p className="mt-3 text-sm font-semibold text-primary">Заявка отправлена</p>}</Card>; }

export function ContactRequest({ requested, isFriend, onRequest }: { requested: boolean; isFriend: boolean; onRequest: () => void }) { return <Card className="p-4"><h2 className="font-bold text-ink">Контакты</h2>{isFriend && requested ? <p className="mt-3 text-sm leading-6 text-ink">Demo-контакт после подтверждения: <strong>Анна доступна через сообщения внутри сценария</strong>. Реальные телефон и email не показываются.</p> : <><p className="mt-2 text-sm leading-6 text-muted">Контакты пользователя скрыты по умолчанию.</p><Button size="sm" variant="secondary" className="mt-3" onClick={onRequest} disabled={requested}>{requested ? "Запрос отправлен" : "Запросить контакты"}</Button></>}</Card>; }

export function DatingRecommendationCard({ user, mutualCommunities, onOpen, onAdd, onHide }: { user: SocialUser; mutualCommunities: string[]; onOpen: () => void; onAdd: () => void; onHide: () => void }) { return <Card className="p-4"><div className="flex items-start gap-3"><Avatar initials={user.avatarLabel} /><div className="min-w-0 flex-1"><h2 className="font-bold text-ink">{user.name}</h2><p className="mt-1 text-sm text-muted">{user.city} · {user.interests.slice(0, 3).join(" · ")}</p></div><IconButton aria-label={`Скрыть рекомендацию ${user.name}`} onClick={onHide}><MoreHorizontal aria-hidden="true" className="h-5 w-5" /></IconButton></div><p className="mt-4 text-sm leading-6 text-ink">Общие сообщества: {mutualCommunities.length ? mutualCommunities.join(", ") : "пока нет"}.</p><p className="mt-2 text-sm leading-6 text-muted">Можно начать с спокойной встречи на открытом событии или в клубе по интересам.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Button size="sm" variant="secondary" onClick={onOpen}>Открыть профиль</Button><Button size="sm" onClick={onAdd}>Добавить в друзья</Button></div></Card>; }
